name: OpenWrt_Build  # 工作流名称

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: 0 19 * * *  # 每天 UTC 时间 19:00（北京时间 03:00）自动运行

env:
  REPO_URL: https://github.com/用户名/源码仓库.git     # ✅ OpenWrt 源码地址（请修改）
  REPO_BRANCH: main                                 # ✅ 源码分支（请修改）
  CONFIG_FILE: configs/your.config                  # ✅ 配置文件路径（请修改）
  DIY_SCRIPT: diy-script.sh                         # 可选 DIY 自定义脚本路径
  CLASH_KERNEL: amd64                               # Clash 内核架构（非必须）
  CACHE_TOOLCHAIN: true                             # 是否启用工具链缓存，加速编译
  UPLOAD_BIN_DIR: false                             # 是否上传完整 bin 目录（调试用）
  FIRMWARE_RELEASE: true                            # 编译完成后是否上传到 GitHub Release
  FIRMWARE_TAG: V1.0                                # Release 固件版本标签
  TZ: Asia/Shanghai                                 # 时区设置为中国标准时间

jobs:
  Build:
    runs-on: ubuntu-22.04  # GitHub 提供的运行环境

    steps:
    - name: 检查服务器性能
      run: |
        echo "分配的 GitHub Actions 虚拟机信息如下："
        lscpu             # 查看 CPU 信息
        free -h           # 查看内存
        df -hT            # 查看磁盘空间

    - name: 初始化构建环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q) || true
        sudo apt-get update
        sudo apt-get install -y $(curl -fsSL https://is.gd/depends_ubuntu_2204)
        sudo timedatectl set-timezone "$TZ"

    - name: 合并磁盘空间
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024         # 增加 swap 交换空间
        temp-reserve-mb: 100       # 保留临时目录空间
        root-reserve-mb: 1024      # 保留根目录空间

    - name: 拉取当前工作仓库（用于读取 config 和脚本）
      uses: actions/checkout@v4

    - name: 克隆 OpenWrt 源码
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        echo "VERSION_INFO=$(git log -1 --pretty=format:'作者: %an\n时间: %cd\n内容: %s\nhash: %H')" >> $GITHUB_ENV

    - name: 执行 DIY 脚本（可选）
      if: env.DIY_SCRIPT != ''
      run: |
        cd $OPENWRT_PATH
        chmod +x ../$DIY_SCRIPT
        ../$DIY_SCRIPT

    - name: 生成平台变量信息
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig > /dev/null 2>&1
        echo "SOURCE_REPO=$(basename -s .git $REPO_URL)" >> $GITHUB_ENV
        echo "DEVICE_TARGET=$(grep CONFIG_TARGET_BOARD .config | cut -d '\"' -f2)" >> $GITHUB_ENV
        echo "DEVICE_SUBTARGET=$(grep CONFIG_TARGET_SUBTARGET .config | cut -d '\"' -f2)" >> $GITHUB_ENV

    - name: 缓存编译工具链（加速二次编译）
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: 准备构建目录结构
      run: |
        [ -e files ] && mv files $OPENWRT_PATH/files
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE $OPENWRT_PATH/.config

    - name: 下载依赖包（DL 目录）
      run: |
        cd $OPENWRT_PATH
        make defconfig
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译 OpenWrt 固件
      id: compile
      run: |
        cd $OPENWRT_PATH
        echo "🔨 使用最大线程数进行编译: $(nproc)"
        if make -j$(nproc); then
          echo "✅ 多线程编译成功"
        else
          echo "⚠️ 多线程失败，尝试单线程详细编译..."
          make -j1 V=s
        fi
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "FILE_DATE=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

    - name: 检查磁盘使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传 bin 目录（可选）
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SOURCE_REPO }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: 整理 ipk/apk 插件并打包
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        mkdir -p packages
        find $OPENWRT_PATH/bin/packages -type f \( -name "*.ipk" -o -name "*.apk" \) -exec cp {} packages/ \;
        [ "$(ls -A packages)" ] && tar -zcf Packages.tar.gz packages
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

    - name: 上传固件到 GitHub Artifact（不发布）
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SOURCE_REPO }}-firmware-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: 上传固件到 GitHub Release（正式发布）
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.DATE }} for ${{ env.FIRMWARE_TAG }}
        tag: ${{ env.FIRMWARE_TAG }}
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          ✅ OpenWrt 固件构建完成！
          - 🔗 源码仓库: ${{ env.REPO_URL }}
          - 🌱 使用分支: ${{ env.REPO_BRANCH }}
          - 🧊 固件版本: ${{ env.FIRMWARE_TAG }}
          - 🌐 默认地址: 192.168.1.1（或自定义）
          - 🔐 默认密码: 无
          - 🛠 最后一次源码提交记录:
            ```
            ${{ env.VERSION_INFO }}
            ```
